name: "フロントエンド"
description: "UI・UX・画面まわりの機能追加・修正"
title: ""

labels: []

body:
  - type: textarea
    id: task
    attributes:
      label: "やる事"
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: "概要"
