name: "Frontend"
description: "UI・UX・画面まわりの機能追加・修正"
title: "[FRONTEND] "

labels: []

body:
  - type: textarea
    id: task
    attributes:
      label: "やること"
      placeholder: "例：チャット画面の送信ボタンUIを修正する"
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: "詳細"
      placeholder: "背景・仕様など"
